<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-BGS5S7GJ" ignored="0" name="127.0.0.1:62001" tests="3" failures="1" timestamp="16 六月 2020 12:45:35 GMT" time="58.144" errors="0">
  <testcase name="test001_login" time="12.117" classname="com.mtx.autotest05.DouBanTests"/>
  <testcase name="test002_uploadHeaderImg" time="19.298" classname="com.mtx.autotest05.DouBanTests"/>
  <testcase name="test003_writeDiary" time="9.843" classname="com.mtx.autotest05.DouBanTests">
    <failure type="java.lang.AssertionError" message="实际值【的好与与  183815】与期望值【的好与与 183815】不一致 expected [的好与与 183815] but found [的好与与  183815]">
      <![CDATA[java.lang.AssertionError: 实际值【的好与与  183815】与期望值【的好与与 183815】不一致 expected [的好与与 183815] but found [的好与与  183815]
at com.crazy.auto.test.Assertion.assertText(Assertion.java:65)
at com.mtx.autotest05.DouBanTests.test003_writeDiary(DouBanTests.java:40)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test003_writeDiary -->
</testsuite> <!-- 127.0.0.1:62001 -->
