<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-BGS5S7GJ" name="com.crazy.auto.keyword.KeywordTestsMobile" tests="2" failures="1" timestamp="13 Jun 2020 07:25:06 GMT" time="25.675" errors="0">
  <testcase name="testKeword" time="12.022" classname="com.crazy.auto.keyword.KeywordTestsMobile"/>
  <testcase name="testKeword" time="13.653" classname="com.crazy.auto.keyword.KeywordTestsMobile">
    <failure type="java.lang.AssertionError" message="退出失败">
      <![CDATA[java.lang.AssertionError: 退出失败
at org.testng.Assert.fail(Assert.java:85)
at com.crazy.auto.keyword.KeywordTestsMobile.testKeword(KeywordTestsMobile.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
at com.crazy.auto.element.ElementOperate.click(ElementOperate.java:108)
at com.crazy.auto.keyword.KeyWordsAction.click(KeyWordsAction.java:160)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.crazy.auto.keyword.KeywordTestsMobile.excuteKeyword(KeywordTestsMobile.java:70)
at com.crazy.auto.keyword.KeywordTestsMobile.testKeword(KeywordTestsMobile.java:50)
... 25 more
]]>
    </failure>
  </testcase> <!-- testKeword -->
</testsuite> <!-- com.crazy.auto.keyword.KeywordTestsMobile -->
